<?php

// This file is part of Ginc.
// no direct access
defined ('Ginc') or die ('no direct script access allowed');


return array (
      /*
      |--------------------------------------------------------------------------
      | Default Character Set
      |--------------------------------------------------------------------------
      |
      | This determines which character set is used by default in various methods
      | that require a character set to be provided.
      |
      */
    'charset'              => 'UTF-8',

    /*
      |--------------------------------------------------------------------------
      | URI PROTOCOL
      |--------------------------------------------------------------------------
      |
      | This item determines which server global should be used to retrieve the
      | URI string.  The default setting of 'AUTO' works for most servers.
      | If your links do not seem to work, try one of the other delicious flavors:
      |
      | 'AUTO'			Default - auto detects
      | 'PATH_INFO'		Uses the PATH_INFO
      | 'QUERY_STRING'	Uses the QUERY_STRING
      | 'REQUEST_URI'		Uses the REQUEST_URI
      | 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
      |
     */
    'uri_protocol'         => 'AUTO',

      /*
      |--------------------------------------------------------------------------
      | Base Site URL
      |--------------------------------------------------------------------------
      |
      | URL to your CodeIgniter root. Typically this will be your base URL,
      | WITH a trailing slash:
      |
      | http://example.com/
      |
      | If this is not set then CodeIgniter will guess the protocol, domain and
      | path to your installation.
      |
      */
    'base_url'         => '',
    
      /*
      |--------------------------------------------------------------------------
      | Index File
      |--------------------------------------------------------------------------
      |
      | Typically this will be your index.php file, unless you've renamed it to
      | something else. If you are using mod_rewrite to remove the page set this
      | variable so that it is blank.
      |
      */
    'index_page'         => 'index.php',

    /*
      |--------------------------------------------------------------------------
      | Allowed URL Characters
      |--------------------------------------------------------------------------
      |
      | This lets you specify with a regular expression which characters are permitted
      | within your URLs.  When someone tries to submit a URL with disallowed
      | characters they will get a warning message.
      |
      | As a security measure you are STRONGLY encouraged to restrict URLs to
      | as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
      |
      | Leave blank to allow all characters -- but only if you are insane.
      |
      | DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
      |
     */
    'permitted_uri_chars'  => 'a-z 0-9~%.:_\-',

      /*
      |--------------------------------------------------------------------------
      | Enable Query Strings
      |--------------------------------------------------------------------------
      |
      | By default CodeIgniter uses search-engine friendly segment based URLs:
      | example.com/who/what/where/
      |
      | By default CodeIgniter enables access to the $_GET array.  If for some
      | reason you would like to disable it, set 'allow_get_array' to FALSE.
      |
      | You can optionally enable standard query string based URLs:
      | example.com?who=me&what=something&where=here
      |
      | Options are: TRUE or FALSE (boolean)
      |
      | The other items let you set the query string 'words' that will
      | invoke your controllers and its functions:
      | example.com/index.php?c=controller&m=function
      |
      | Please note that some of the helpers won't work as expected when
      | this feature is enabled, since CodeIgniter is designed primarily to
      | use segment based URLs.
      |
     */
    'allow_get_array'      => TRUE,
    'enable_query_strings' => FALSE,
    'controller_trigger'   => 'c',
    'function_trigger'     => 'm',
    'directory_trigger'    => 'd', // experimental not currently in use

    /*
      |--------------------------------------------------------------------------
      | URL suffix
      |--------------------------------------------------------------------------
      |
      | This option allows you to add a suffix to all URLs generated by CodeIgniter.
      | For more information please see the user guide:
      |
      | http://codeigniter.com/user_guide/general/urls.html
     */
    'url_suffix'       => '.html',

    'web_master_email' => 'webmaster@Ginc-project.com',

      /*
      |--------------------------------------------------------------------------
      | Default Language
      |--------------------------------------------------------------------------
      |
      | This determines which set of language files should be used. Make sure
      | there is an available translation if you intend to use something other
      | than english.
      |
      */
    'language'         => 'en_US',


    'theme'         => 'default',

    /*
      |--------------------------------------------------------------------------
      | Output Compression
      |--------------------------------------------------------------------------
      |
      | Enables Gzip output compression for faster page loads.  When enabled,
      | the output class will test whether your server supports Gzip.
      | Even if it does, however, not all browsers support compression
      | so enable only if you are reasonably sure your visitors can handle it.
      |
      | VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
      | means you are prematurely outputting something to your browser. It could
      | even be a line of whitespace at the end of one of your scripts.  For
      | compression to work, nothing can be sent before the output buffer is called
      | by the output class.  Do not 'echo' any values with compression enabled.
      |
      */
    'compress_output'         => FALSE,

    // enable cache
    'cache'         => TRUE,

    // encryption Config
    'encryption_key' => 'ThisKey',
    'encryption_mode' => 'cfb', # cbc , cfb , ofb , ecb
    'encryption_cipher' => 'rijndael-256',

    // Security Setting
    'XSS_FILTERING' => TRUE, # Global XSS Filtering
    'STRCHECK' => TRUE,
    'enable_csrf' => TRUE,


    // DeBuger Setting
    'PHP_ERROR_HANDLER'      => TRUE,
    'SHOW_ERROR_MESSAGE'     => TRUE,
    'WRITE_LOG_MESSAGE'      => TRUE,
    'SHOW_CODE_SOURCE'       => TRUE,
    'PHP_EXCEPTION_HANDLER'  => TRUE,
    'SHOW_EXCEPTION_MESSAGE' => TRUE,
    'LOAD_ERROR_HANDLER'     => TRUE,
    'DB_ERROR_DISPLAY'       => TRUE,
    
    /*
    |--------------------------------------------------------------------------
    | Reverse Proxy IPs
    |--------------------------------------------------------------------------
    |
    | If your server is behind a reverse proxy, you must whitelist the proxy IP
    | addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
    | header in order to properly identify the visitor's IP address.
    | Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
    |
    */
    'proxy_ips' => '',
);
